// Objective-C API for talking to github.com/dpwiese/sample Go package.
//   gobind -lang=objc github.com/dpwiese/sample
//
// File is generated by gobind. Do not edit.

#ifndef __Sample_H__
#define __Sample_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


/**
 * AddTwoNumbers does the obvious
 */
FOUNDATION_EXPORT double SampleAddTwoNumbers(double num1, double num2);

/**
 * ConcatenateStrings does the obvious
 */
FOUNDATION_EXPORT NSString* _Nonnull SampleConcatenateStrings(NSString* _Nullable string1, NSString* _Nullable string2);

/**
 * IncrementSliceElements takes a base64 string representing an array of floats decodes it and increments each element of the array by 1
 */
FOUNDATION_EXPORT NSString* _Nonnull SampleIncrementSliceElements(NSString* _Nullable str);

/**
 * SolveBVPWithInputs requires user specified parameters to solve BVP
 */
FOUNDATION_EXPORT NSString* _Nonnull SampleSolveBVPWithInputs(NSString* _Nullable configString);

/**
 * SolveBVPWithoutInputs solves BVP with fixed parameters
 */
FOUNDATION_EXPORT NSString* _Nonnull SampleSolveBVPWithoutInputs(void);

#endif
