const BASE_UUID_PREFIX = '0000';
const BASE_BLE_UUID_SUFFIX = '0000-1000-8000-00805f9b34fb';

export const BleUuid = {
  // Heart rate service and characteristics
  HEART_RATE_SERVICE: `${BASE_UUID_PREFIX}180d-${BASE_BLE_UUID_SUFFIX}`,
  HEART_RATE_MEASUREMENT_CHARACTERISTIC: `${BASE_UUID_PREFIX}2a37-${BASE_BLE_UUID_SUFFIX}`,

  // Heart data service
  HEART_RATE_DATA_SERVICE: `${BASE_UUID_PREFIX}1800-${BASE_BLE_UUID_SUFFIX}`,
  HEART_RATE_DEVICE_NAME_CHARACTERISTIC: `${BASE_UUID_PREFIX}2a00-${BASE_BLE_UUID_SUFFIX}`,

  // Heart device information service
  HEART_RATE_DEVICE_INFORMATION_SERVICE: `${BASE_UUID_PREFIX}180a-${BASE_BLE_UUID_SUFFIX}`,
  HEART_RATE_MANUFACTURER_NAME_CHARACTERISTIC: `${BASE_UUID_PREFIX}2a29-${BASE_BLE_UUID_SUFFIX}`,
  HEART_RATE_HARDWARE_REVISION_NUMBER_CHARACTERISTIC: `${BASE_UUID_PREFIX}2a27-${BASE_BLE_UUID_SUFFIX}`,
  HEART_RATE_FIRMWARE_REVISION_NUMBER_CHARACTERISTIC: `${BASE_UUID_PREFIX}2a26-${BASE_BLE_UUID_SUFFIX}`,
  HEART_RATE_SERIAL_NUMBER_CHARACTERISTIC: `${BASE_UUID_PREFIX}2a25-${BASE_BLE_UUID_SUFFIX}`,

  // Heart battery service
  HEART_RATE_BATTERY_SERVICE: `${BASE_UUID_PREFIX}180f-${BASE_BLE_UUID_SUFFIX}`,
  HEART_RATE_BATTERY_CHARACTERISTIC: `${BASE_UUID_PREFIX}2a19-${BASE_BLE_UUID_SUFFIX}`,
};
