require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

# See: https://github.com/CocoaPods/CocoaPods/issues/8891#issuecomment-573301570
post_install do |installer|
  installer.pods_project.targets.each do |target|
    # Fix bundle targets' 'Signing Certificate' to 'Sign to Run Locally'
    if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
      target.build_configurations.each do |config|
        config.build_settings['CODE_SIGN_IDENTITY[sdk=macosx*]'] = '-'
      end
    end
  end
end

target 'ReactNativeCatalyst' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # Can remove MultiplatformBleAdapter once react-native-ble-plx is used in package.json from production release
  pod 'MultiplatformBleAdapter', :git => 'git@github.com:dpwiese/MultiPlatformBleAdapter.git', :commit => 'e1cc5411167147804225a8141c294a8795ddfc36'
  pod 'react-native-ble-plx', :path => '../node_modules/react-native-ble-plx'

  target 'ReactNativeCatalystTests' do
    inherit! :complete
    # Pods for testing
  end

  use_native_modules!
end

target 'ReactNativeCatalyst-tvOS' do
  # Pods for ReactNativeCatalyst-tvOS

  target 'ReactNativeCatalyst-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
